### ISSUE TITLE
View not Found – yii\base\ViewNotFoundException

### ISSUE THREAD

**Issue by dimonpvt1236** [NullRefExcep/yii2-full-admin#2]
After registration throw exception:

View not Found – yii\base\ViewNotFoundException
The view file does not exist: /var/www/yii2-first/vendor/nullref/yii2-full-admin/src/modules/user/views/message.php

In submodule User not exists view file message.php

**Comment by ZAYEC77** [comment]
hello 
could you provide an example of your app config?

**Comment by ZAYEC77** [comment]
fixed
please check the last master version

**Comment by dimonpvt1236** [comment]
thanks, this worked
